name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      AWS_REGION: ap-southeast-2
      ECR_REPOSITORY: 468460113372.dkr.ecr.ap-southeast-2.amazonaws.com/school-ecr

    defaults:
      run:
        shell: bash
        working-directory: backend/src

    steps:
    - uses: actions/checkout@v3
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build the Docker image
      run: docker build . --file ./School.Api/Dockerfile --tag ${{ env.ECR_REPOSITORY }}:${{ env.GITHUB_SHA }}

#    - name: Build the Docker image
#      uses: docker/build-push-action@v2
#      with:
#        context: .
#        push: true
#        tags: ${{ env.ECR_REPOSITORY }}:${{ env.GITHUB_SHA }}
#        env:
#          DOCKER_CLI_EXPERIMENTAL: enabled

    - name: Push the Docker image to Amazon ECR
      uses: aws-actions/amazon-ecr-push@v1
      with:
        repository-url: ${{ env.ECR_REPOSITORY }}
        tags: ${{ env.GITHUB_SHA }}
        force: true
        registry-id: ${{ steps.login-ecr.outputs.registry-id }}
